// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8ECi_0DGujH4hPBfYxssMjjqFlTTAZA',
    appId: '1:647909230394:web:e5f2d529250c79d6bbb203',
    messagingSenderId: '647909230394',
    projectId: 'chatappflut-29513',
    authDomain: 'chatappflut-29513.firebaseapp.com',
    storageBucket: 'chatappflut-29513.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrLkvvbvceSmhaldSb00jS6c1lOqGyF3I',
    appId: '1:647909230394:android:cc98ed049444d932bbb203',
    messagingSenderId: '647909230394',
    projectId: 'chatappflut-29513',
    storageBucket: 'chatappflut-29513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6bbgLM-PTT1okOlgqYkD1DkGF-W4UN0',
    appId: '1:647909230394:ios:3ce98c7d94563785bbb203',
    messagingSenderId: '647909230394',
    projectId: 'chatappflut-29513',
    storageBucket: 'chatappflut-29513.appspot.com',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6bbgLM-PTT1okOlgqYkD1DkGF-W4UN0',
    appId: '1:647909230394:ios:4063d6d607521478bbb203',
    messagingSenderId: '647909230394',
    projectId: 'chatappflut-29513',
    storageBucket: 'chatappflut-29513.appspot.com',
    iosBundleId: 'com.example.flutterChatApplication.RunnerTests',
  );
}
